### ISSUE TITLE
Bug not allowing vertical movement

### ISSUE THREAD

**Issue by dimitri16h** [bootcamp-s18/frogger#10]
When frogger is in the left most position of any row, he is unable to move up or down on the y axis.

**Comment by kevin-moore-729** [comment]
that would explain why the leftmost home space is impossible to reach

**Comment by dimitri16h** [comment]
Bug seems to be fixed in the most recent pull request, I will close this once it is approved

**Comment by TheErikWolfe** [comment]
^
