### ISSUE TITLE
Make the home spaces work

### ISSUE THREAD

**Issue by TheErikWolfe** [bootcamp-s18/frogger#5]
## Make the home spaces work
* The home spaces should fill with a frog sprite when you make it into one.  
** You can't move into a space filled with a frog sprite
* If you fill all 5 of them you proceed to the next level.

**Comment by kevin-moore-729** [comment]
Locally I have home space functionality as follows:

- as frog jumps into empty home space, home space is occupied by frog sprite for remainder of game
- if frog jumps into occupied home space, lives are decremented and frog is reset

**Comment by kevin-moore-729** [comment]
Currently in home-space branch:

- functionality as described above
- homespaces clear if all filled
- player gains extra life if all homespaces filled

**Comment by TheErikWolfe** [comment]
Is this issue finished or was there more that we could do?

**Comment by kevin-moore-729** [comment]
I guess the desired outcome of the issue was met so we could close it, but we discussed cleaning up the clumsy code so we should make note of that elsewhere
